// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: soc_lvgl

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_screen
void ui_screen_screen_init(void);
lv_obj_t * ui_screen;
lv_obj_t * ui_bar;
lv_obj_t * ui_date;
lv_obj_t * ui_time;
lv_obj_t * ui_power;
lv_obj_t * ui_powericon;
lv_obj_t * ui_powervalue;
lv_obj_t * ui_chats;
lv_obj_t * ui_temperaturecontainer;
lv_obj_t * ui_temperature;
lv_obj_t * ui_temperaturelabel;
lv_obj_t * ui_humiditycontainer;
lv_obj_t * ui_humidity;
lv_obj_t * ui_humiditylabel;
lv_obj_t * ui_functions;
lv_obj_t * ui_refreshbutton;
lv_obj_t * ui_refreshlabel;
lv_obj_t * ui_switchbutton;
lv_obj_t * ui_switchlabel;
lv_obj_t * ui_modebutton;
lv_obj_t * ui_modelabel;
lv_obj_t * ui_otherbutton;
lv_obj_t * ui_otherlabel;
lv_timer_t * touch_key_refresh_timer;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_screen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_screen);
}
