// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.2.2
// Project name: soc_lvgl

#include "../ui.h"

void ui_screen_screen_init(void)
{
    ui_screen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_screen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_screen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bar = lv_obj_create(ui_screen);
    lv_obj_remove_style_all(ui_bar);
    lv_obj_set_height(ui_bar, 24);
    lv_obj_set_width(ui_bar, lv_pct(100));
    lv_obj_set_align(ui_bar, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_bar, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_date = lv_label_create(ui_bar);
    lv_obj_set_width(ui_date, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_date, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_date, 8);
    lv_obj_set_y(ui_date, 0);
    lv_obj_set_align(ui_date, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_date, "2025/04/10");
    lv_obj_set_style_text_font(ui_date, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_time = lv_label_create(ui_bar);
    lv_obj_set_width(ui_time, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_time, 80);
    lv_obj_set_y(ui_time, 0);
    lv_obj_set_align(ui_time, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_time, "12:12");
    lv_obj_set_style_text_font(ui_time, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_power = lv_obj_create(ui_bar);
    lv_obj_remove_style_all(ui_power);
    lv_obj_set_width(ui_power, 50);
    lv_obj_set_height(ui_power, 24);
    lv_obj_set_align(ui_power, LV_ALIGN_RIGHT_MID);
    lv_obj_remove_flag(ui_power, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_powericon = lv_bar_create(ui_power);
    lv_bar_set_value(ui_powericon, 50, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_powericon, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_powericon, 40);
    lv_obj_set_height(ui_powericon, 16);
    lv_obj_set_align(ui_powericon, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_powericon, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_powericon, lv_color_hex(0x00BA35), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_powericon, 64, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_powericon, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_powericon, lv_color_hex(0x00BA35), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_powericon, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_powericon, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_powericon,
                                                                                                lv_obj_get_style_pad_right(ui_powericon, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_powervalue = lv_label_create(ui_power);
    lv_obj_set_width(ui_powervalue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_powervalue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_powervalue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_powervalue, "50%");
    lv_obj_set_style_text_font(ui_powervalue, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_chats = lv_obj_create(ui_screen);
    lv_obj_remove_style_all(ui_chats);
    lv_obj_set_height(ui_chats, 193);
    lv_obj_set_width(ui_chats, lv_pct(100));
    lv_obj_set_x(ui_chats, 0);
    lv_obj_set_y(ui_chats, 24);
    lv_obj_set_align(ui_chats, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_chats, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_temperaturecontainer = lv_obj_create(ui_chats);
    lv_obj_remove_style_all(ui_temperaturecontainer);
    lv_obj_set_height(ui_temperaturecontainer, 200);
    lv_obj_set_width(ui_temperaturecontainer, lv_pct(50));
    lv_obj_set_align(ui_temperaturecontainer, LV_ALIGN_LEFT_MID);
    lv_obj_remove_flag(ui_temperaturecontainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_temperature = lv_chart_create(ui_temperaturecontainer);
    lv_obj_set_width(ui_temperature, lv_pct(65));
    lv_obj_set_height(ui_temperature, lv_pct(70));
    lv_obj_set_x(ui_temperature, 15);
    lv_obj_set_y(ui_temperature, -30);
    lv_obj_set_align(ui_temperature, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_temperature,
                    LV_OBJ_FLAG_OVERFLOW_VISIBLE);      //make scales visible - Should it be forced to True?
    //lv_obj_remove_flag( ui_temperature, LV_OBJ_FLAG_SCROLLABLE );    //no chart-zoom in LVGL9 - Shouldn't it be forced to False?
    lv_chart_set_type(ui_temperature, LV_CHART_TYPE_BAR);
    lv_obj_set_style_radius(ui_temperature, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_temperature, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_temperature, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_temperature_Xaxis = lv_scale_create(ui_temperature);
    lv_scale_set_mode(ui_temperature_Xaxis, LV_SCALE_MODE_HORIZONTAL_BOTTOM);
    lv_obj_set_size(ui_temperature_Xaxis, lv_pct(100), 50);
    lv_obj_set_align(ui_temperature_Xaxis, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_y(ui_temperature_Xaxis, 50 + lv_obj_get_style_pad_bottom(ui_temperature,
                                                                        LV_PART_MAIN) + lv_obj_get_style_border_width(ui_temperature, LV_PART_MAIN));
    lv_obj_set_style_line_width(ui_temperature_Xaxis, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_temperature_Xaxis, 1, LV_PART_ITEMS);   //LVGL-9.1 ticks are thicker by default
    lv_obj_set_style_line_width(ui_temperature_Xaxis, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_temperature_Xaxis, 4, LV_PART_ITEMS);      //minor tick length
    lv_obj_set_style_length(ui_temperature_Xaxis, 8, LV_PART_INDICATOR);      //major tick length
    lv_scale_set_range(ui_temperature_Xaxis, 0, 5 > 0 ? 5 - 1 : 0);
    lv_scale_set_total_tick_count(ui_temperature_Xaxis, (5 > 0 ? 5 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_temperature_Xaxis, 2 >= 1 ? 2 : 1);
    ui_temperature_Yaxis1 = lv_scale_create(ui_temperature);
    lv_scale_set_mode(ui_temperature_Yaxis1, LV_SCALE_MODE_VERTICAL_LEFT);
    lv_obj_set_size(ui_temperature_Yaxis1, 50, lv_pct(100));
    lv_obj_set_align(ui_temperature_Yaxis1, LV_ALIGN_LEFT_MID);
    lv_obj_set_x(ui_temperature_Yaxis1, -50 - lv_obj_get_style_pad_left(ui_temperature,
                                                                        LV_PART_MAIN) - lv_obj_get_style_border_width(ui_temperature, LV_PART_MAIN) + 2);
    lv_obj_set_style_line_width(ui_temperature_Yaxis1, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_temperature_Yaxis1, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_temperature_Yaxis1, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_temperature_Yaxis1, 4, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_temperature_Yaxis1, 8, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_total_tick_count(ui_temperature_Yaxis1, (5 > 0 ? 5 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_temperature_Yaxis1, 2 >= 1 ? 2 : 1);
    ui_temperature_Yaxis2 = lv_scale_create(ui_temperature);
    lv_scale_set_mode(ui_temperature_Yaxis2, LV_SCALE_MODE_VERTICAL_RIGHT);
    lv_obj_set_size(ui_temperature_Yaxis2, 25, lv_pct(100));
    lv_obj_set_align(ui_temperature_Yaxis2, LV_ALIGN_RIGHT_MID);
    lv_obj_set_x(ui_temperature_Yaxis2, 25 + lv_obj_get_style_pad_right(ui_temperature,
                                                                        LV_PART_MAIN) + lv_obj_get_style_border_width(ui_temperature, LV_PART_MAIN) + 1);
    lv_obj_set_style_line_width(ui_temperature_Yaxis2, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_temperature_Yaxis2, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_temperature_Yaxis2, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_temperature_Yaxis2, 4, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_temperature_Yaxis2, 8, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_total_tick_count(ui_temperature_Yaxis2, (0 > 0 ? 0 - 1 : 0) * 0 + 1);
    lv_scale_set_major_tick_every(ui_temperature_Yaxis2, 0 >= 1 ? 0 : 1);
    lv_scale_set_label_show(ui_temperature_Yaxis2, false);
    lv_chart_series_t * ui_temperature_series_1 = lv_chart_add_series(ui_temperature, lv_color_hex(0x808080),
                                                                      LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_temperature_series_1_array[] = { 0, 10, 20, 40, 80, 80, 40, 20, 10, 0 };
    lv_chart_set_ext_y_array(ui_temperature, ui_temperature_series_1, ui_temperature_series_1_array);

    lv_obj_set_style_text_font(ui_temperature_Xaxis, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_temperature_Yaxis1, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_temperature_Yaxis2, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    //This workaround (an invisible outline) is needed because without it chart overflow-visible doesn't work in LVGL-9.1
    lv_obj_set_style_outline_pad(ui_temperature, LV_MAX3(50, 50, 25),
                                 LV_PART_MAIN | LV_STATE_DEFAULT);   //workaround for ineffective 'overflow visible' flag
    lv_obj_set_style_outline_width(ui_temperature, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_temperaturelabel = lv_label_create(ui_temperaturecontainer);
    lv_obj_set_width(ui_temperaturelabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_temperaturelabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_temperaturelabel, 15);
    lv_obj_set_y(ui_temperaturelabel, 10);
    lv_obj_set_align(ui_temperaturelabel, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_temperaturelabel, "Temperature");
    lv_obj_set_style_text_font(ui_temperaturelabel, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_humiditycontainer = lv_obj_create(ui_chats);
    lv_obj_remove_style_all(ui_humiditycontainer);
    lv_obj_set_height(ui_humiditycontainer, 200);
    lv_obj_set_width(ui_humiditycontainer, lv_pct(50));
    lv_obj_set_align(ui_humiditycontainer, LV_ALIGN_RIGHT_MID);
    lv_obj_remove_flag(ui_humiditycontainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_humidity = lv_chart_create(ui_humiditycontainer);
    lv_obj_set_width(ui_humidity, lv_pct(65));
    lv_obj_set_height(ui_humidity, lv_pct(70));
    lv_obj_set_x(ui_humidity, -15);
    lv_obj_set_y(ui_humidity, -30);
    lv_obj_set_align(ui_humidity, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_humidity, LV_OBJ_FLAG_OVERFLOW_VISIBLE);      //make scales visible - Should it be forced to True?
    //lv_obj_remove_flag( ui_humidity, LV_OBJ_FLAG_SCROLLABLE );    //no chart-zoom in LVGL9 - Shouldn't it be forced to False?
    lv_chart_set_type(ui_humidity, LV_CHART_TYPE_LINE);
    lv_obj_set_style_radius(ui_humidity, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_humidity, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_humidity, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_humidity_Xaxis = lv_scale_create(ui_humidity);
    lv_scale_set_mode(ui_humidity_Xaxis, LV_SCALE_MODE_HORIZONTAL_BOTTOM);
    lv_obj_set_size(ui_humidity_Xaxis, lv_pct(100), 50);
    lv_obj_set_align(ui_humidity_Xaxis, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_y(ui_humidity_Xaxis, 50 + lv_obj_get_style_pad_bottom(ui_humidity,
                                                                     LV_PART_MAIN) + lv_obj_get_style_border_width(ui_humidity, LV_PART_MAIN));
    lv_obj_set_style_line_width(ui_humidity_Xaxis, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_humidity_Xaxis, 1, LV_PART_ITEMS);   //LVGL-9.1 ticks are thicker by default
    lv_obj_set_style_line_width(ui_humidity_Xaxis, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_humidity_Xaxis, 4, LV_PART_ITEMS);      //minor tick length
    lv_obj_set_style_length(ui_humidity_Xaxis, 8, LV_PART_INDICATOR);      //major tick length
    lv_scale_set_range(ui_humidity_Xaxis, 0, 5 > 0 ? 5 - 1 : 0);
    lv_scale_set_total_tick_count(ui_humidity_Xaxis, (5 > 0 ? 5 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_humidity_Xaxis, 2 >= 1 ? 2 : 1);
    ui_humidity_Yaxis1 = lv_scale_create(ui_humidity);
    lv_scale_set_mode(ui_humidity_Yaxis1, LV_SCALE_MODE_VERTICAL_LEFT);
    lv_obj_set_size(ui_humidity_Yaxis1, 50, lv_pct(100));
    lv_obj_set_align(ui_humidity_Yaxis1, LV_ALIGN_LEFT_MID);
    lv_obj_set_x(ui_humidity_Yaxis1, -50 - lv_obj_get_style_pad_left(ui_humidity,
                                                                     LV_PART_MAIN) - lv_obj_get_style_border_width(ui_humidity, LV_PART_MAIN) + 2);
    lv_obj_set_style_line_width(ui_humidity_Yaxis1, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_humidity_Yaxis1, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_humidity_Yaxis1, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_humidity_Yaxis1, 4, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_humidity_Yaxis1, 8, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_total_tick_count(ui_humidity_Yaxis1, (0 > 0 ? 0 - 1 : 0) * 0 + 1);
    lv_scale_set_major_tick_every(ui_humidity_Yaxis1, 0 >= 1 ? 0 : 1);
    lv_scale_set_label_show(ui_humidity_Yaxis1, false);
    ui_humidity_Yaxis2 = lv_scale_create(ui_humidity);
    lv_scale_set_mode(ui_humidity_Yaxis2, LV_SCALE_MODE_VERTICAL_RIGHT);
    lv_obj_set_size(ui_humidity_Yaxis2, 25, lv_pct(100));
    lv_obj_set_align(ui_humidity_Yaxis2, LV_ALIGN_RIGHT_MID);
    lv_obj_set_x(ui_humidity_Yaxis2, 25 + lv_obj_get_style_pad_right(ui_humidity,
                                                                     LV_PART_MAIN) + lv_obj_get_style_border_width(ui_humidity, LV_PART_MAIN) + 1);
    lv_obj_set_style_line_width(ui_humidity_Yaxis2, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_humidity_Yaxis2, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_humidity_Yaxis2, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_humidity_Yaxis2, 4, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_humidity_Yaxis2, 8, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_total_tick_count(ui_humidity_Yaxis2, (5 > 0 ? 5 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_humidity_Yaxis2, 2 >= 1 ? 2 : 1);
    lv_chart_series_t * ui_humidity_series_1 = lv_chart_add_series(ui_humidity, lv_color_hex(0x808080),
                                                                   LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_humidity_series_1_array[] = { 0, 10, 20, 40, 80, 80, 40, 20, 10, 0 };
    lv_chart_set_ext_y_array(ui_humidity, ui_humidity_series_1, ui_humidity_series_1_array);

    lv_obj_set_style_text_font(ui_humidity_Xaxis, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_humidity_Yaxis1, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_humidity_Yaxis2, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    //This workaround (an invisible outline) is needed because without it chart overflow-visible doesn't work in LVGL-9.1
    lv_obj_set_style_outline_pad(ui_humidity, LV_MAX3(50, 50, 25),
                                 LV_PART_MAIN | LV_STATE_DEFAULT);   //workaround for ineffective 'overflow visible' flag
    lv_obj_set_style_outline_width(ui_humidity, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_humiditylabel = lv_label_create(ui_humiditycontainer);
    lv_obj_set_width(ui_humiditylabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_humiditylabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_humiditylabel, -15);
    lv_obj_set_y(ui_humiditylabel, 10);
    lv_obj_set_align(ui_humiditylabel, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_humiditylabel, "Humidity");
    lv_obj_set_style_text_font(ui_humiditylabel, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_functions = lv_obj_create(ui_screen);
    lv_obj_remove_style_all(ui_functions);
    lv_obj_set_height(ui_functions, 55);
    lv_obj_set_width(ui_functions, lv_pct(100));
    lv_obj_set_align(ui_functions, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_functions, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_functions, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_functions, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_functions, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_functions, -50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_refreshbutton = lv_button_create(ui_functions);
    lv_obj_set_height(ui_refreshbutton, 30);
    lv_obj_set_width(ui_refreshbutton, lv_pct(15));
    lv_obj_set_align(ui_refreshbutton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_refreshbutton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_refreshbutton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_refreshbutton, 15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_refreshlabel = lv_label_create(ui_refreshbutton);
    lv_obj_set_width(ui_refreshlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_refreshlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_refreshlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_refreshlabel, "Refresh");
    lv_obj_set_style_text_font(ui_refreshlabel, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_switchbutton = lv_button_create(ui_functions);
    lv_obj_set_height(ui_switchbutton, 30);
    lv_obj_set_width(ui_switchbutton, lv_pct(15));
    lv_obj_set_align(ui_switchbutton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_switchbutton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_switchbutton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_switchbutton, 15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_switchlabel = lv_label_create(ui_switchbutton);
    lv_obj_set_width(ui_switchlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_switchlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_switchlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_switchlabel, "Switch");
    lv_obj_set_style_text_font(ui_switchlabel, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_modebutton = lv_button_create(ui_functions);
    lv_obj_set_height(ui_modebutton, 30);
    lv_obj_set_width(ui_modebutton, lv_pct(15));
    lv_obj_set_align(ui_modebutton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_modebutton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_modebutton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_modebutton, 15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_modelabel = lv_label_create(ui_modebutton);
    lv_obj_set_width(ui_modelabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_modelabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_modelabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_modelabel, "Mode");
    lv_obj_set_style_text_font(ui_modelabel, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_otherbutton = lv_button_create(ui_functions);
    lv_obj_set_height(ui_otherbutton, 30);
    lv_obj_set_width(ui_otherbutton, lv_pct(15));
    lv_obj_set_align(ui_otherbutton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_otherbutton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_otherbutton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_otherbutton, 15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_otherlabel = lv_label_create(ui_otherbutton);
    lv_obj_set_width(ui_otherlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_otherlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_otherlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_otherlabel, "Other");
    lv_obj_set_style_text_font(ui_otherlabel, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

}
