// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: test_fps

#include "../ui.h"

void ui_Screen_screen_init(void) {
    ui_Screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_Screen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container = lv_obj_create(ui_Screen);
    lv_obj_remove_style_all(ui_Container);
    lv_obj_set_width(ui_Container, Container_Size);
    lv_obj_set_height(ui_Container, Container_Size);
    lv_obj_clear_flag(ui_Container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_Image = lv_img_create(ui_Container);
    lv_obj_set_width(ui_Image, Image_Size);
    lv_obj_set_height(ui_Image, Image_Size);
    lv_obj_set_align(ui_Image, LV_ALIGN_BOTTOM_RIGHT);
    lv_img_set_src(ui_Image, &Image_File);
    lv_obj_clear_flag(ui_Image, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                                    LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                                    LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                                    LV_OBJ_FLAG_SCROLL_MOMENTUM |
                                    LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags
    HorizontalMovement_Animation(ui_Image, 0);
}
